#!/usr/bin/env node
/**
 * Regenerate the golden-file corpus.
 *
 *   npm run golden:update -w @fhir-mcp/server
 *
 * Rewrites every src/tests/golden/<case>/expected.json from current behaviour.
 *
 * READ THE DIFF. The corpus exists so that a change in masking output arrives
 * as a reviewable diff instead of as silence. Regenerating without reading it
 * converts the corpus from a gate into a rubber stamp, and the whole point of
 * checking these files in is lost.
 *
 * This script REFUSES to run in CI. A pipeline that can regenerate its own
 * expectations cannot fail on them.
 */
import { spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';

const CI_VARS = ['CI', 'GITHUB_ACTIONS', 'BUILD_NUMBER', 'TF_BUILD'];
const inCI = CI_VARS.find((name) => process.env[name]);

if (inCI) {
  console.error(
    `\n[golden:update] REFUSING to run: ${inCI} is set.\n\n` +
      '  The golden corpus must never be regenerated by CI. If a golden case is\n' +
      '  red in the pipeline, the masked output changed -- regenerate locally,\n' +
      '  read the diff, and commit it deliberately.\n'
  );
  process.exit(1);
}

const require = createRequire(import.meta.url);
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..');

const result = spawnSync(
  process.execPath,
  [
    '--experimental-vm-modules',
    require.resolve('jest/bin/jest'),
    'golden-corpus',
    ...process.argv.slice(2)
  ],
  {
    cwd: packageRoot,
    stdio: 'inherit',
    env: {
      ...process.env,
      GOLDEN_UPDATE: '1',
      NODE_OPTIONS: [process.env.NODE_OPTIONS, '--experimental-vm-modules']
        .filter(Boolean)
        .join(' ')
    }
  }
);

if (result.status === 0) {
  console.log(
    '\n[golden:update] Rewrote expected.json for every case.\n' +
      '  Now run `git diff` and read it line by line before committing.\n'
  );
}

process.exit(result.status ?? 1);